import { Oswald } from "next/font/google";
import "./globals.css";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "700"], // Choose the weights you need
  variable: "--font-oswald", // This creates the CSS variable
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth dark">
      <body
        className={`${oswald.variable} font-sans antialiased bg-white dark:bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
