import { Type } from "@google/genai";
import { DOMAIN_SLUGS } from "./domains";

// The exact JSON shape we force the classifier's answer into. Passed as Gemini's
// `responseSchema`, it constrains the model to exactly these fields and types, so
// downstream code can trust the result without defensive parsing.
export const CLASSIFIER_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    domain: {
      type: Type.STRING,
      enum: DOMAIN_SLUGS, // taxonomy lives in domains.js — one source of truth
      description: "The single best top-level category for the user's goal.",
    },
    sub_domain: {
      type: Type.STRING,
      description:
        "Specific canonical slug within the domain, lowercase-hyphenated, " +
        "e.g. 'rust-programming', 'fat-loss', 'calculus-final-exam'.",
    },
    confidence: {
      type: Type.NUMBER,
      description: "0-1: how confident the classification of `domain` is.",
    },
    multi_domain: {
      type: Type.BOOLEAN,
      description: "True if the goal genuinely spans more than one domain.",
    },
    sensitive: {
      type: Type.BOOLEAN,
      description:
        "True if the goal touches medical, mental-health, financial-risk, or " +
        "other sensitive territory that needs careful handling.",
    },
  },
  required: ["domain", "sub_domain", "confidence", "multi_domain", "sensitive"],
  propertyOrdering: [
    "domain", "sub_domain", "confidence", "multi_domain", "sensitive",
  ],
};

// How the UI should render each interview answer input. The planner reads the
// answer text regardless; `type` only shapes the onboarding form.
export const QUESTION_TYPES = ["text", "single_select", "multi_select", "number", "date"];

// The onboarding interview: a short list of tailored questions whose answers
// give the planner everything it needs to build a personalized plan. Passed as
// Gemini's `responseSchema` so the model returns exactly this shape.
export const INTERVIEW_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    questions: {
      type: Type.ARRAY,
      description: "4-6 onboarding questions, ordered as they should be asked.",
      items: {
        type: Type.OBJECT,
        properties: {
          key: {
            type: Type.STRING,
            description:
              "Stable snake_case slug for the dimension this question captures " +
              "(e.g. 'success_criteria', 'capacity', 'starting_point', " +
              "'constraints', 'deadline'). Becomes the key in goals.source_metadata.",
          },
          question: {
            type: Type.STRING,
            description: "The question text shown to the user. One idea, plain language.",
          },
          type: {
            type: Type.STRING,
            enum: QUESTION_TYPES,
            description: "Which input control the UI should render for the answer.",
          },
          options: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description:
              "3-5 choices for single_select / multi_select questions. " +
              "Empty for other types.",
          },
          placeholder: {
            type: Type.STRING,
            description: "Short example answer for text / number inputs. May be empty.",
          },
        },
        required: ["key", "question", "type"],
        propertyOrdering: ["key", "question", "type", "options", "placeholder"],
      },
    },
  },
  required: ["questions"],
  propertyOrdering: ["questions"],
};

// How a day's target is measured. Maps to habit_schedules.target_metric (jsonb).
export const METRIC_TYPES = ["duration", "count", "reps", "distance", "boolean", "none"];

// --- Plan schema (generated by the planner, mirrors the DB tables) -----------
// A single checklist item within a day's session.
const SUB_TASK_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    name: {
      type: Type.STRING,
      description: "One concrete sub-task, e.g. 'Wall sit 30s', 'Write the add-item command'.",
    },
  },
  required: ["name"],
  propertyOrdering: ["name"],
};

// What to hit on a given day. `type:"none"` is a plain yes/no habit (no number).
const TARGET_METRIC_SCHEMA = {
  type: Type.OBJECT,
  description: "The day's target. Use type 'none' for a simple yes/no habit.",
  properties: {
    type: {
      type: Type.STRING,
      enum: METRIC_TYPES,
      description: "How the target is measured.",
    },
    value: {
      type: Type.NUMBER,
      description: "Numeric target (e.g. 45, 5, 3). Omit for 'boolean'/'none'.",
    },
    unit: {
      type: Type.STRING,
      description: "Unit for value, e.g. 'minutes', 'problems', 'rounds', 'km'.",
    },
  },
  required: ["type"],
  propertyOrdering: ["type", "value", "unit"],
};

// One (habit, weekday) row: the dynamic per-day definition. -> habit_schedules.
const SCHEDULE_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    day_of_week: {
      type: Type.INTEGER,
      description: "0=Sunday .. 6=Saturday.",
    },
    variant_label: {
      type: Type.STRING,
      description: "Short name for that day's session, e.g. 'Upper body', 'Trees: 5 problems', 'Rest'.",
    },
    is_rest_day: {
      type: Type.BOOLEAN,
      description: "True = a deliberate rest day (auto-satisfies, never breaks the streak).",
    },
    sub_tasks: {
      type: Type.ARRAY,
      items: SUB_TASK_SCHEMA,
      description: "Checklist for the day. Empty on rest days or single-action habits.",
    },
    target_metric: TARGET_METRIC_SCHEMA,
  },
  required: ["day_of_week", "variant_label", "is_rest_day"],
  propertyOrdering: ["day_of_week", "variant_label", "is_rest_day", "sub_tasks", "target_metric"],
};

// One habit plus its weekly schedule. -> habits (+ habit_schedules children).
const HABIT_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    name: {
      type: Type.STRING,
      description: "The habit's name, e.g. 'Morning movement', 'Rust reps'.",
    },
    is_routine: {
      type: Type.BOOLEAN,
      description: "True if it's a multi-step routine (has sub-tasks); false for a single simple action.",
    },
    schedules: {
      type: Type.ARRAY,
      items: SCHEDULE_SCHEMA,
      description:
        "One entry per day this habit is defined (active days + any explicit rest days). " +
        "1-7 entries; day_of_week must be unique within a habit.",
    },
  },
  required: ["name", "is_routine", "schedules"],
  propertyOrdering: ["name", "is_routine", "schedules"],
};

// The full starter plan the planner emits for a goal. Returned by /api/plan and
// (later) written to goals + habits + habit_schedules.
export const PLAN_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    goal: {
      type: Type.OBJECT,
      properties: {
        title: {
          type: Type.STRING,
          description: "Short, motivating title for the goal.",
        },
        description: {
          type: Type.STRING,
          description: "One-line description of the goal.",
        },
        category: {
          type: Type.STRING,
          enum: DOMAIN_SLUGS,
          description: "The goal's domain — matches the classification.",
        },
        target_date: {
          type: Type.STRING,
          description: "Hard deadline as YYYY-MM-DD, or an empty string if open-ended.",
        },
        rationale: {
          type: Type.STRING,
          description:
            "2-3 sentences on why this plan fits THIS person, citing their answers. Shown to the user.",
        },
      },
      required: ["title", "description", "category", "target_date", "rationale"],
      propertyOrdering: ["title", "description", "category", "target_date", "rationale"],
    },
    habits: {
      type: Type.ARRAY,
      items: HABIT_SCHEMA,
      description: "2-4 starter habits — the FIRST phase only, not the whole journey.",
    },
  },
  required: ["goal", "habits"],
  propertyOrdering: ["goal", "habits"],
};
